name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget \
        module-init-tools
    - name: Clone source code
      run: |
        git clone --depth=1 https://gitee.com/hanwckf/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        ./clean_toolchain
        ./build_toolchain
        sed -i -e 's/CONFIG_FIRMWARE_INCLUDE_OPENVPN=n/CONFIG_FIRMWARE_INCLUDE_OPENVPN=y/g' -e 's/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=y/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n/g' \
        -e 's/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=y/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n/g' -e /opt/rt-n56u/trunk/configs/templates/K2P-5.0.config
        cd /opt/rt-n56u/trunk
        ./clear_tree
        fakeroot ./build_firmware_modify K2P-5.0
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: trunk/images
#     - name: scp-pipeline
#   # You may pin to the exact commit or the version.
#   # uses: cross-the-world/scp-pipeline@b4d86397129250eb940fabdc3f7a435436d2503a
#       uses: cross-the-world/scp-pipeline@v1.2.1
#       with:
#         # ssh remote host
#         host: ${{secrets.PI_HOST}}
#         # ssh remote port
#         port: ${{secrets.PI_PORT}}
#         # ssh remote user
#         user: ${{secrets.PI_USER}}
#         # content of ssh private key. ex raw content of ~/.ssh/id_rsa
#         key: ${{secrets.PI_PASSWORD}}
#         # ssh remote password
# #         pass: ${{secrets.PI_PASSWORD}}
#         # connection timeout to remote host
# #         connect_timeout: # optional, default is 30s
#         # source to copy
#         local: /opt/rt-n56.tar.gz
#         # destination for copy
#         remote: /tmp
#         # scp from local to remote
# #         scp: # optional
